name = "DeepQLearning"
uuid = "de0a67f4-c691-11e8-0034-5fc6e16e22d3"
repo = "https://github.com/JuliaPOMDP/DeepQLearning.jl"
version = "0.7.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CommonRLInterface = "d842c3ba-07a1-494f-bbec-f5741b0a3e98"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
POMDPLinter = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"

[compat]
BSON = "0.2, 0.3"
CommonRLInterface = "0.2, 0.3"
EllipsisNotation = "1"
Flux = "0.14"
POMDPLinter = "0.1"
POMDPTools = "0.1"
POMDPs = "0.9, 1"
Parameters = "0.12"
StatsBase = "0.32, 0.33, 0.34"
TensorBoardLogger = "0.1"
julia = "1.9"

[extras]
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["POMDPModels", "StaticArrays", "Test"]
